/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.AdaptadorFacturas;
import controlador.ControlDatos;
import java.io.IOException;
import java.math.BigDecimal;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.Set;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.xml.parsers.ParserConfigurationException;
import javax.xml.transform.TransformerException;
import modelo.Articulos;
import modelo.FacturasCab;
import modelo.FacturasLin;
import modelo.FacturasLinId;
import org.xml.sax.SAXException;

/**
 *
 * @author Alukard
 */
public class DialogNuevaFactura extends java.awt.Dialog {
    private int ultimaLin;
    private FacturasCab facturaCab;
    private ControlDatos control;
    private int indiceFacturas;
    private AdaptadorFacturas exportador;
    public DialogNuevaFactura(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ultimaLin = 1; //La primera linea de la factura
        exportador = new AdaptadorFacturas(); //Instanciamos el controlador de exportaciones
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        campoNumFac = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        campoFechaFac = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        campoDniCliente = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaFacturas = new javax.swing.JTable();
        listaArticulos = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        campoNomArt = new javax.swing.JTextField();
        botonAgregarArt = new javax.swing.JButton();
        botonModArt = new javax.swing.JButton();
        botonBorrarArt = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        campoCantidad = new javax.swing.JFormattedTextField();
        botonCrearOferta = new javax.swing.JButton();
        botonCargarOferta = new javax.swing.JButton();
        campoDescuento = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setTitle("New bill");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jLabel1.setText("Bill number");

        campoNumFac.setEditable(false);
        campoNumFac.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel2.setText("Bill date");

        campoFechaFac.setEditable(false);
        campoFechaFac.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel3.setText("Client DNI");

        campoDniCliente.setEditable(false);
        campoDniCliente.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tablaFacturas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Line", "Product", "Amount", "Value", "Discount", "VAT"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaFacturas);

        listaArticulos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                listaArticulosItemStateChanged(evt);
            }
        });

        jLabel4.setText("Product");

        campoNomArt.setEditable(false);

        botonAgregarArt.setText("Add");
        botonAgregarArt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarArtActionPerformed(evt);
            }
        });

        botonModArt.setText("Edit");
        botonModArt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModArtActionPerformed(evt);
            }
        });

        botonBorrarArt.setText("Remove");
        botonBorrarArt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBorrarArtActionPerformed(evt);
            }
        });

        jLabel5.setText("Amount");

        campoCantidad.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        campoCantidad.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        botonCrearOferta.setText("New offer");
        botonCrearOferta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearOfertaActionPerformed(evt);
            }
        });

        botonCargarOferta.setText("Load offer");
        botonCargarOferta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCargarOfertaActionPerformed(evt);
            }
        });

        campoDescuento.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel6.setText("Discount");

        jLabel7.setText("%");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 56, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)))
                            .addComponent(listaArticulos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonAgregarArt)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(campoDescuento, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                                    .addComponent(campoCantidad))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7))
                            .addComponent(campoNomArt, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonBorrarArt, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botonModArt, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botonCrearOferta, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botonCargarOferta, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(campoNumFac))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(campoFechaFac))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(campoDniCliente))
                .addGap(137, 137, 137))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {campoNumFac, jLabel1});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {campoFechaFac, jLabel2});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {campoDniCliente, jLabel3});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {botonBorrarArt, botonCargarOferta, botonCrearOferta, botonModArt});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoNumFac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoFechaFac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoDniCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 11, Short.MAX_VALUE)
                        .addComponent(botonBorrarArt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonModArt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonCrearOferta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonCargarOferta)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(listaArticulos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoNomArt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(campoCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonAgregarArt)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void botonAgregarArtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarArtActionPerformed
         try{
            Articulos art = (Articulos) listaArticulos.getSelectedItem(); //Cogemos el articulo seleccionado del comboBox
            if(Integer.parseInt(campoCantidad.getText()) > 0 && campoCantidad.getText().length() != 0 && campoDescuento.getText().length() != 0){ //Se controla que los campos no esten vacios
                if(Double.parseDouble(campoDescuento.getText()) >= 0 && Double.parseDouble(campoDescuento.getText()) <= 100){
                    if(control.restarStock(art, Double.parseDouble(campoCantidad.getText())) == 0){ // y que queda stock suficiente

                        FacturasLin linea = new FacturasLin(); //Creamos una nueva linea de factura
                        FacturasLinId linId = new FacturasLinId(); //Con su id para relacionarla a la factura
                        linId.setLineafac(ultimaLin);
                        linId.setNumfac(facturaCab.getNumfac());
                        Set<FacturasLin> setLineas = facturaCab.getFacturasLins();
                        linea.setId(linId);
                        linea.setArticulos(art);
                        linea.setCantidad(BigDecimal.valueOf(Long.valueOf(campoCantidad.getText())));
                        linea.setPrecio(art.getPrecio());
                        linea.setDtolinea(BigDecimal.valueOf(Double.valueOf(campoDescuento.getText())));
                        linea.setIvalinea(art.getPorciva()); //Añadimos los atributos de la linea
                        setLineas.add(linea); //Añadimos la linea al set de lineas
                        facturaCab.setFacturasLins(setLineas); //Añadimos el set de lineas a la factura
                        linea.setFacturasCab(facturaCab); //Añadimos a la linea la cabecera de la factura
                        control.aniadirLinea(facturaCab); //Añadimos la linea a la BD
                        control.calcularTot(linea); //Calculamos el nuevo total de la factura
                        ultimaLin++; //Avanzamos en uno el numero de linea
                        borrarTabla(); //Borramos la tabla para eliminar registros anteriores
                        rellenarTabla(); //La rellenamos con los nuevos
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "Insufficient stock.");
                        ultimaLin++; //Se debe avanzar la linea o da error
                    }
                }
                else{
                    JOptionPane.showMessageDialog(null, "Discount must be between 0 and 100");
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "Check amount and discount fields.");
            }
        }
        catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(null, "Insert a correct amount.");
        }
    }//GEN-LAST:event_botonAgregarArtActionPerformed

    private void botonBorrarArtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBorrarArtActionPerformed
        indiceFacturas = tablaFacturas.getSelectedRow(); //Se coge el indice del registro seleccioando
        
        if(indiceFacturas != -1){ //Si se ha seleccionado un registro
            
            FacturasLin linea = (FacturasLin) tablaFacturas.getValueAt(indiceFacturas, 0); //Cogemos el objeto FacturasLin del registro seleccionado
            Set<FacturasLin> lineas = facturaCab.getFacturasLins();
            lineas.remove(linea);
            facturaCab.setFacturasLins(lineas);
            control.borrarLinea(linea);
            
            borrarTabla();
            rellenarTabla();
        }
        else{
            JOptionPane.showMessageDialog(null, "Select a row.");
        }
    }//GEN-LAST:event_botonBorrarArtActionPerformed

    private void listaArticulosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_listaArticulosItemStateChanged
        Articulos art = (Articulos) listaArticulos.getSelectedItem();
        campoNomArt.setText(art.getDescripcion()); //Cada vez que seleccionamos un articulo se pone su nombre en el campo adyacente
    }//GEN-LAST:event_listaArticulosItemStateChanged

    private void botonModArtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModArtActionPerformed
        indiceFacturas = tablaFacturas.getSelectedRow(); //Cogemos el indice del registro seleccionado
        if(indiceFacturas != -1){ //Si se ha seleccionado uno
            FacturasLin linea = (FacturasLin) tablaFacturas.getValueAt(indiceFacturas, 0); //Cogemos la linea
            linea.setCantidad(BigDecimal.valueOf(Long.valueOf(campoCantidad.getText()))); 
            linea.setArticulos((Articulos) listaArticulos.getSelectedItem()); //Editamos el contenido
            borrarTabla();
            rellenarTabla();
        }
        else{
            JOptionPane.showMessageDialog(null, "Select a row.");
        }
    }//GEN-LAST:event_botonModArtActionPerformed

    private void botonCrearOfertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearOfertaActionPerformed
    JFileChooser ruta = new JFileChooser();
    if(ruta.showOpenDialog(null) == JFileChooser.APPROVE_OPTION){
        try{
            exportador.crearOferta(facturaCab, ruta.getSelectedFile()); //Se crea la oferta en el fichero seleccionado
        }
        catch(TransformerException | ParserConfigurationException ex){
            JOptionPane.showMessageDialog(null, "Error when creating the file.");
        }
    }
    else{
        JOptionPane.showMessageDialog(null, "Offert not created.");
    }
    }//GEN-LAST:event_botonCrearOfertaActionPerformed

    private void botonCargarOfertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCargarOfertaActionPerformed
        JFileChooser ruta = new JFileChooser();
        if(ruta.showOpenDialog(null) == JFileChooser.APPROVE_OPTION){
            try {
                facturaCab = exportador.cargarOferta(ruta.getSelectedFile(), facturaCab); //Cargamos un fichero xml y lo añadimos el objeto FacturasLin que contiene a la BD
                rellenarTabla();
            } catch (ParserConfigurationException ex) {
                JOptionPane.showMessageDialog(null, "Error loading file");
            } catch (SAXException | IOException ex){
                JOptionPane.showMessageDialog(null, "Error loading file.");
            }
        }
    }//GEN-LAST:event_botonCargarOfertaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogNuevaFactura dialog = new DialogNuevaFactura(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    public void setFacturaCab(FacturasCab factura){ //Se ejecuta al abrir el dialog y se le pasa la factura en cuestion para trabajar con ella
        control = new ControlDatos();
        facturaCab = factura; 
        campoNumFac.setText(String.valueOf(factura.getNumfac()));
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yy");
        campoFechaFac.setText(formato.format(factura.getFechafac()));
        campoDniCliente.setText(factura.getClientes().getDnicif());
        List<Articulos> articulos = control.recibirArticulos();
        articulos.forEach((art) -> {
            listaArticulos.addItem(art);
        });
    }
    
    private void rellenarTabla(){ //Rellena la tabla con sus registros correspondientes
        DefaultTableModel modelo = (DefaultTableModel) tablaFacturas.getModel();
        Set<FacturasLin> linea = facturaCab.getFacturasLins();
        List<FacturasLin> lineasOrdenadas = new ArrayList<>(linea);
        lineasOrdenadas.sort(Comparator.comparing(FacturasLin::getLinea));
        lineasOrdenadas.forEach((lin) -> {
            modelo.addRow(new Object[]{lin, lin.getArticulos(),lin.getCantidad(), lin.getPrecio(), lin.getDtolinea(), lin.getIvalinea()});
        });
    }
    
    private void borrarTabla(){ //Quita los registros de la tabla
        DefaultTableModel modelo = (DefaultTableModel) tablaFacturas.getModel();
        while(tablaFacturas.getRowCount() != 0){
            modelo.removeRow(0);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregarArt;
    private javax.swing.JButton botonBorrarArt;
    private javax.swing.JButton botonCargarOferta;
    private javax.swing.JButton botonCrearOferta;
    private javax.swing.JButton botonModArt;
    private javax.swing.JFormattedTextField campoCantidad;
    private javax.swing.JTextField campoDescuento;
    private javax.swing.JTextField campoDniCliente;
    private javax.swing.JTextField campoFechaFac;
    private javax.swing.JTextField campoNomArt;
    private javax.swing.JTextField campoNumFac;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<Articulos> listaArticulos;
    private javax.swing.JTable tablaFacturas;
    // End of variables declaration//GEN-END:variables
}
