/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import modelo.Clientes;
import controlador.ControlDatos;
import javax.swing.JOptionPane;
/**
 *
 * @author Alukard
 */
public class DialogClientes extends java.awt.Dialog {
    private ControlDatos control;
    private Clientes cli;
    public DialogClientes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        control = new ControlDatos();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        campoClienteNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        campoClientesDni = new javax.swing.JTextField();
        botonEditarNombre = new javax.swing.JButton();
        botonBorrarCliente = new javax.swing.JButton();

        setTitle("Customer");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jLabel1.setText("Name");

        jLabel2.setText("DNI");

        campoClientesDni.setEditable(false);

        botonEditarNombre.setText("Modify");
        botonEditarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEditarNombreActionPerformed(evt);
            }
        });

        botonBorrarCliente.setText("Delete");
        botonBorrarCliente.setToolTipText("");
        botonBorrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBorrarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoClienteNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoClientesDni, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(botonBorrarCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonEditarNombre)))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {campoClienteNombre, campoClientesDni});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(campoClientesDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(campoClienteNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonEditarNombre)
                    .addComponent(botonBorrarCliente))
                .addContainerGap())
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void botonEditarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEditarNombreActionPerformed
        cli.setNombrecli(campoClienteNombre.getText());
        if(control.editarCliente(cli) == 0){ //Coge el nombre del campo y edita al cliente
            JOptionPane.showMessageDialog(null, "Customer updated.");
            closeDialog(null);
        }
    }//GEN-LAST:event_botonEditarNombreActionPerformed

    private void botonBorrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBorrarClienteActionPerformed
        int seleccion = JOptionPane.showConfirmDialog( //Se pregunta si se quiere borrar
                            null, "Delete customer?",
                            "Deleting customer",
                            JOptionPane.YES_NO_OPTION);
                    if(seleccion==JOptionPane.YES_OPTION){
                        int error = control.borrarCliente(cli); //Si elige que si se borra
                        if(error == 0){
                            JOptionPane.showMessageDialog(null, "Removed.");
                        }
                        if(error == 1){
                            JOptionPane.showMessageDialog(null, "You can't remove a customer associated to another table.");
                        }
                    }
                    if(seleccion==JOptionPane.NO_OPTION){
                         JOptionPane.showMessageDialog(null, "Cancelled");
                    }
    }//GEN-LAST:event_botonBorrarClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogClientes dialog = new DialogClientes(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public void rellenarCampos(Clientes cliente){ //Se llama al metodo tras abrir el dialog para cargar los datos de los campos
        campoClienteNombre.setText(cliente.getNombrecli());
        campoClientesDni.setText(cliente.getDnicif());
        cli = cliente; 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBorrarCliente;
    private javax.swing.JButton botonEditarNombre;
    private javax.swing.JTextField campoClienteNombre;
    private javax.swing.JTextField campoClientesDni;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
